### ISSUE TITLE
Create schematron instance for BRICR outside of T24

### ISSUE THREAD

**Issue by nllong** [BuildingSync/selection-tool#14]
Presently, the BRICR use case only allows T24 climate zones, however, the https://github.com/BuildingSync/BuildingSync-gem is using the same use case to define a level zero model which allows for climate zones outside of CA. 

The proposal is to create a new use case (named BRICR-ASHRAE?) which relaxes the constraints of the BRICR use case for an international audience.

**Comment by kflemin** [comment]
use schematron for this.

**Comment by corymosiman12** [comment]
I believe this is covered by the [L000_OpenStudio_Simulation.sch](https://github.com/BuildingSync/TestSuite/blob/L100_Schematron/spec/use_cases/schema2.0.0/L000_OpenStudio_Simulation.sch) file.

Two example XML files are provided in the [HVAC System Examples](https://github.com/BuildingSync/TestSuite/tree/L100_Schematron#hvac-system-examples) table with:
- MLOD = L000
- Use Case = OpenStudio_Simulation

@nllong or @kflemin - if you believe this is correct, I think this can be closed.

**Comment by corymosiman12** [comment]
@nllong @kflemin thoughts on above?

**Comment by nllong** [comment]
Yep, we can close. L000 OpenStudio Simulation should cover the use case. (Especially with the newly transformed BSync files on the BRICR instance.)
