### ISSUE TITLE
test out script to generate permission schematron document

### ISSUE THREAD

**Issue by kflemin** [BuildingSync/selection-tool#25]
Test out the Ruby script that generates a Schematron document that “permit”s all of BuildingSync XML schema.

**Comment by corymosiman12** [comment]
Successfully completed.  From email on 11/21/19:

`Running his app.rb code generates the Ruby code required (BuildingSync_schematron.rb, attached) to then generate the BuildingSync_schematron.xml file used to validate a BuildingSync file.`

See the README -> Overview section [here](https://github.com/corymosiman12/test_suite).  Need to bring this entire `test_suite` repo somewhere into the schema / selection-tool repos, not sure where yet.  @kflemin @nllong thoughts?

**Comment by corymosiman12** [comment]
New [TestSuite](https://github.com/BuildingSync/TestSuite) repo created.
