### ISSUE TITLE
Use case for BSync to OpenStudio - Level 100

### ISSUE THREAD

**Issue by kflemin** [BuildingSync/selection-tool#27]
create use case schematron file for bsync to openstudio - level 1

**Comment by corymosiman12** [comment]
This is complete for:
- MLOD = L100
- Use Case = OpenStudio_Simulation

[L100_OpenStudio_Simulation.sch](https://github.com/BuildingSync/TestSuite/blob/L100_Schematron/spec/use_cases/schema2.0.0/L100_OpenStudio_Simulation.sch)

@nllong @kflemin I believe this can be closed.
