### ISSUE TITLE
Use Case for Standard 211 Level 0

### ISSUE THREAD

**Issue by kflemin** [BuildingSync/selection-tool#30]
create schematron file for standard 211 use case

**Comment by corymosiman12** [comment]
Are these basically the same thing now? https://github.com/BuildingSync/selection-tool/issues/14

If so, I believe these are both covered by the [L000_OpenStudio_Simulation.sch](https://github.com/BuildingSync/TestSuite/blob/L100_Schematron/spec/use_cases/schema2.0.0/L000_OpenStudio_Simulation.sch) file.

Two example XML files are provided in the [HVAC System Examples](https://github.com/BuildingSync/TestSuite/tree/L100_Schematron#hvac-system-examples) table with:
- MLOD = L000
- Use Case = OpenStudio_Simulation

@nllong or @kflemin, if you agree, I think these can both be closed.

**Comment by corymosiman12** [comment]
Sorry, please ignore the comment above. If I understand correctly, this issue is referring to:
- MLOD = L000
- Use Case = Audit

This is currently in progress via the https://github.com/BuildingSync/TestSuite/blob/L100_Schematron/spec/use_cases/schema2.0.0/L000_Prelim_Analysis.sch

**Comment by nllong** [comment]
Hey Cory, I thought that this was completed?

**Comment by corymosiman12** [comment]
No - probably 75%.
